# Continuous integration and pull request validation builds for the
# main and maintenance branches.
name: CI Build

on:
  push:
    branches: [ master, maint/* ]
  pull_request:
    branches: [ master, maint/* ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: source
        fetch-depth: 0
    - name: Set up a workflow
      working-directory: source
      run: |
        pwd
        git config user.name 'Test'
        git config user.email 'test@example.com'
        touch .github/workflows/new_file.yml
        git add .github/workflows/new_file.yml
        git commit -mtest
        git push origin master:test
